// CFB Phase 2 school config — all 86 schools of the source-map universe.
// GENERATED (scratchpad/gen-config.js) from docs/cfb-source-map.dumps.json + curated
// venueTz / conference2026 / canonical-slug maps. `id` is the CANONICAL slug
// (slugifySchool of the common short name) so cfbGames.homeSchoolId lines up with
// the conferenceGame rule; `officialScheduleUrl` + `wikiTeamPage` are the sweep's
// render-confirmed URLs. `wikiNotYetCreated` marks the 4 timing-stranded G5 schools
// whose Wikipedia 2026 page did not exist at sweep time (defer 2nd source).

export interface CfbSchoolConfig2026 {
  id: string;
  name: string; // display, e.g. "Alabama"
  nick: string;
  officialDomain: string;
  officialScheduleUrl: string; // sweep render-confirmed
  wikiTeamPage: string | null; // resolved Wikipedia title, null if not-yet-created
  wikiNotYetCreated: boolean;
  venueTz: string; // IANA home-venue tz (kickoff.tz default; corroborator interprets Wikipedia times in this tz)
  conference2026: string;
}

export const SCHOOLS_2026: CfbSchoolConfig2026[] = [
  { id: "alabama", name: "Alabama", nick: "Crimson Tide", officialDomain: "rolltide.com", officialScheduleUrl: "https://rolltide.com/sports/football/schedule", wikiTeamPage: "2026 Alabama Crimson Tide football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "georgia", name: "Georgia", nick: "Bulldogs", officialDomain: "georgiadogs.com", officialScheduleUrl: "https://georgiadogs.com/sports/football/schedule", wikiTeamPage: "2026 Georgia Bulldogs football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "SEC" },
  { id: "lsu", name: "LSU", nick: "Tigers", officialDomain: "lsusports.net", officialScheduleUrl: "https://lsusports.net/sports/football/schedule", wikiTeamPage: "2026 LSU Tigers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "tennessee", name: "Tennessee", nick: "Volunteers", officialDomain: "utsports.com", officialScheduleUrl: "https://utsports.com/sports/football/schedule", wikiTeamPage: "2026 Tennessee Volunteers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "SEC" },
  { id: "texas", name: "Texas", nick: "Longhorns", officialDomain: "texassports.com", officialScheduleUrl: "https://texassports.com/sports/football/schedule", wikiTeamPage: "2026 Texas Longhorns football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "oklahoma", name: "Oklahoma", nick: "Sooners", officialDomain: "soonersports.com", officialScheduleUrl: "https://soonersports.com/sports/football/schedule", wikiTeamPage: "2026 Oklahoma Sooners football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "auburn", name: "Auburn", nick: "Tigers", officialDomain: "auburntigers.com", officialScheduleUrl: "https://auburntigers.com/sports/football/schedule", wikiTeamPage: "2026 Auburn Tigers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "florida", name: "Florida", nick: "Gators", officialDomain: "floridagators.com", officialScheduleUrl: "https://floridagators.com/sports/football/schedule", wikiTeamPage: "2026 Florida Gators football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "SEC" },
  { id: "texas-am", name: "Texas A&M", nick: "Aggies", officialDomain: "12thman.com", officialScheduleUrl: "https://12thman.com/sports/football/schedule", wikiTeamPage: "2026 Texas A&M Aggies football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "ole-miss", name: "Ole Miss", nick: "Rebels", officialDomain: "olemisssports.com", officialScheduleUrl: "https://olemisssports.com/sports/football/schedule", wikiTeamPage: "2026 Ole Miss Rebels football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "mississippi-state", name: "Mississippi State", nick: "Bulldogs", officialDomain: "hailstate.com", officialScheduleUrl: "https://hailstate.com/sports/football/schedule", wikiTeamPage: "2026 Mississippi State Bulldogs football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "arkansas", name: "Arkansas", nick: "Razorbacks", officialDomain: "arkansasrazorbacks.com", officialScheduleUrl: "https://arkansasrazorbacks.com/arkansas-2026-schedule-unveiled", wikiTeamPage: "2026 Arkansas Razorbacks football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "kentucky", name: "Kentucky", nick: "Wildcats", officialDomain: "ukathletics.com", officialScheduleUrl: "https://ukathletics.com/sports/football/schedule", wikiTeamPage: "2026 Kentucky Wildcats football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "SEC" },
  { id: "south-carolina", name: "South Carolina", nick: "Gamecocks", officialDomain: "gamecocksonline.com", officialScheduleUrl: "https://gamecocksonline.com/sports/football/schedule", wikiTeamPage: "2026 South Carolina Gamecocks football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "SEC" },
  { id: "missouri", name: "Missouri", nick: "Tigers", officialDomain: "mutigers.com", officialScheduleUrl: "https://mutigers.com/sports/football/schedule", wikiTeamPage: "2026 Missouri Tigers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "vanderbilt", name: "Vanderbilt", nick: "Commodores", officialDomain: "vucommodores.com", officialScheduleUrl: "https://vucommodores.com/sports/football/schedule", wikiTeamPage: "2026 Vanderbilt Commodores football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "SEC" },
  { id: "ohio-state", name: "Ohio State", nick: "Buckeyes", officialDomain: "ohiostatebuckeyes.com", officialScheduleUrl: "https://ohiostatebuckeyes.com/sports/football/schedule", wikiTeamPage: "2026 Ohio State Buckeyes football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "michigan", name: "Michigan", nick: "Wolverines", officialDomain: "mgoblue.com", officialScheduleUrl: "https://mgoblue.com/sports/football/schedule", wikiTeamPage: "2026 Michigan Wolverines football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "penn-state", name: "Penn State", nick: "Nittany Lions", officialDomain: "gopsusports.com", officialScheduleUrl: "https://gopsusports.com/sports/football/schedule", wikiTeamPage: "2026 Penn State Nittany Lions football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "oregon", name: "Oregon", nick: "Ducks", officialDomain: "goducks.com", officialScheduleUrl: "https://goducks.com/sports/football/schedule", wikiTeamPage: "2026 Oregon Ducks football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Big Ten" },
  { id: "usc", name: "USC", nick: "Trojans", officialDomain: "usctrojans.com", officialScheduleUrl: "https://usctrojans.com/sports/football/schedule", wikiTeamPage: "2026 USC Trojans football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Big Ten" },
  { id: "ucla", name: "UCLA", nick: "Bruins", officialDomain: "uclabruins.com", officialScheduleUrl: "https://uclabruins.com/sports/football/schedule", wikiTeamPage: "2026 UCLA Bruins football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Big Ten" },
  { id: "washington", name: "Washington", nick: "Huskies", officialDomain: "gohuskies.com", officialScheduleUrl: "https://gohuskies.com/sports/football/schedule", wikiTeamPage: "2026 Washington Huskies football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Big Ten" },
  { id: "wisconsin", name: "Wisconsin", nick: "Badgers", officialDomain: "uwbadgers.com", officialScheduleUrl: "https://uwbadgers.com/sports/football/schedule", wikiTeamPage: "2026 Wisconsin Badgers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "nebraska", name: "Nebraska", nick: "Cornhuskers", officialDomain: "huskers.com", officialScheduleUrl: "https://huskers.com/sports/football/schedule", wikiTeamPage: "2026 Nebraska Cornhuskers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "iowa", name: "Iowa", nick: "Hawkeyes", officialDomain: "hawkeyesports.com", officialScheduleUrl: "https://hawkeyesports.com/sports/football/schedule", wikiTeamPage: "2026 Iowa Hawkeyes football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "michigan-state", name: "Michigan State", nick: "Spartans", officialDomain: "msuspartans.com", officialScheduleUrl: "https://msuspartans.com/sports/football/schedule", wikiTeamPage: "2026 Michigan State Spartans football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "minnesota", name: "Minnesota", nick: "Golden Gophers", officialDomain: "gophersports.com", officialScheduleUrl: "https://gophersports.com/sports/football/schedule", wikiTeamPage: "2026 Minnesota Golden Gophers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "illinois", name: "Illinois", nick: "Fighting Illini", officialDomain: "fightingillini.com", officialScheduleUrl: "https://fightingillini.com/sports/football/schedule", wikiTeamPage: "2026 Illinois Fighting Illini football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "indiana", name: "Indiana", nick: "Hoosiers", officialDomain: "iuhoosiers.com", officialScheduleUrl: "https://iuhoosiers.com/sports/football/schedule", wikiTeamPage: "2026 Indiana Hoosiers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "maryland", name: "Maryland", nick: "Terrapins", officialDomain: "umterps.com", officialScheduleUrl: "https://umterps.com/sports/football/schedule", wikiTeamPage: "2026 Maryland Terrapins football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "rutgers", name: "Rutgers", nick: "Scarlet Knights", officialDomain: "scarletknights.com", officialScheduleUrl: "https://scarletknights.com/sports/football/schedule", wikiTeamPage: "2026 Rutgers Scarlet Knights football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "northwestern", name: "Northwestern", nick: "Wildcats", officialDomain: "nusports.com", officialScheduleUrl: "https://nusports.com/sports/football/schedule", wikiTeamPage: "2026 Northwestern Wildcats football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big Ten" },
  { id: "purdue", name: "Purdue", nick: "Boilermakers", officialDomain: "purduesports.com", officialScheduleUrl: "https://purduesports.com/sports/football/schedule", wikiTeamPage: "2026 Purdue Boilermakers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big Ten" },
  { id: "clemson", name: "Clemson", nick: "Tigers", officialDomain: "clemsontigers.com", officialScheduleUrl: "https://clemsontigers.com/sports/football/schedule", wikiTeamPage: "2026 Clemson Tigers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "florida-state", name: "Florida State", nick: "Seminoles", officialDomain: "seminoles.com", officialScheduleUrl: "https://seminoles.com/sports/football/schedule", wikiTeamPage: "2026 Florida State Seminoles football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "miami", name: "Miami", nick: "Hurricanes", officialDomain: "miamihurricanes.com", officialScheduleUrl: "https://miamihurricanes.com/sports/football/schedule", wikiTeamPage: "2026 Miami Hurricanes football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "north-carolina", name: "North Carolina", nick: "Tar Heels", officialDomain: "goheels.com", officialScheduleUrl: "https://goheels.com/sports/football/schedule", wikiTeamPage: "2026 North Carolina Tar Heels football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "nc-state", name: "NC State", nick: "Wolfpack", officialDomain: "gopack.com", officialScheduleUrl: "https://gopack.com/sports/football/schedule", wikiTeamPage: "2026 NC State Wolfpack football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "virginia", name: "Virginia", nick: "Cavaliers", officialDomain: "virginiasports.com", officialScheduleUrl: "https://virginiasports.com/sports/football/schedule", wikiTeamPage: "2026 Virginia Cavaliers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "virginia-tech", name: "Virginia Tech", nick: "Hokies", officialDomain: "hokiesports.com", officialScheduleUrl: "https://hokiesports.com/sports/football/schedule", wikiTeamPage: "2026 Virginia Tech Hokies football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "louisville", name: "Louisville", nick: "Cardinals", officialDomain: "gocards.com", officialScheduleUrl: "https://gocards.com/sports/football/schedule", wikiTeamPage: "2026 Louisville Cardinals football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "pittsburgh", name: "Pittsburgh", nick: "Panthers", officialDomain: "pittsburghpanthers.com", officialScheduleUrl: "https://pittsburghpanthers.com/sports/football/schedule", wikiTeamPage: "2026 Pittsburgh Panthers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "duke", name: "Duke", nick: "Blue Devils", officialDomain: "goduke.com", officialScheduleUrl: "https://goduke.com/sports/football/schedule", wikiTeamPage: "2026 Duke Blue Devils football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "wake-forest", name: "Wake Forest", nick: "Demon Deacons", officialDomain: "godeacs.com", officialScheduleUrl: "https://godeacs.com/sports/football/schedule", wikiTeamPage: "2026 Wake Forest Demon Deacons football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "georgia-tech", name: "Georgia Tech", nick: "Yellow Jackets", officialDomain: "ramblinwreck.com", officialScheduleUrl: "https://ramblinwreck.com/georgia-techs-2026-football-schedule-is-set", wikiTeamPage: "2026 Georgia Tech Yellow Jackets football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "boston-college", name: "Boston College", nick: "Eagles", officialDomain: "bceagles.com", officialScheduleUrl: "https://bceagles.com/sports/football/schedule", wikiTeamPage: "2026 Boston College Eagles football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "syracuse", name: "Syracuse", nick: "Orange", officialDomain: "cuse.com", officialScheduleUrl: "https://cuse.com/sports/football/schedule", wikiTeamPage: "2026 Syracuse Orange football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "ACC" },
  { id: "california", name: "California", nick: "Golden Bears", officialDomain: "calbears.com", officialScheduleUrl: "https://calbears.com/sports/football/schedule", wikiTeamPage: "2026 California Golden Bears football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "ACC" },
  { id: "stanford", name: "Stanford", nick: "Cardinal", officialDomain: "gostanford.com", officialScheduleUrl: "https://gostanford.com/sports/football/schedule", wikiTeamPage: "2026 Stanford Cardinal football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "ACC" },
  { id: "smu", name: "SMU", nick: "Mustangs", officialDomain: "smumustangs.com", officialScheduleUrl: "https://smumustangs.com/sports/football/schedule", wikiTeamPage: "2026 SMU Mustangs football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "ACC" },
  { id: "utah", name: "Utah", nick: "Utes", officialDomain: "utahutes.com", officialScheduleUrl: "https://utahutes.com/sports/football/schedule", wikiTeamPage: "2026 Utah Utes football team", wikiNotYetCreated: false, venueTz: "America/Denver", conference2026: "Big 12" },
  { id: "kansas-state", name: "Kansas State", nick: "Wildcats", officialDomain: "kstatesports.com", officialScheduleUrl: "https://kstatesports.com/sports/football/schedule", wikiTeamPage: "2026 Kansas State Wildcats football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "oklahoma-state", name: "Oklahoma State", nick: "Cowboys", officialDomain: "okstate.com", officialScheduleUrl: "https://okstate.com/sports/football/schedule", wikiTeamPage: "2026 Oklahoma State Cowboys football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "kansas", name: "Kansas", nick: "Jayhawks", officialDomain: "kuathletics.com", officialScheduleUrl: "https://kuathletics.com/sports/football/schedule", wikiTeamPage: "2026 Kansas Jayhawks football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "baylor", name: "Baylor", nick: "Bears", officialDomain: "baylorbears.com", officialScheduleUrl: "https://baylorbears.com/sports/football/schedule", wikiTeamPage: "2026 Baylor Bears football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "tcu", name: "TCU", nick: "Horned Frogs", officialDomain: "gofrogs.com", officialScheduleUrl: "https://gofrogs.com/sports/football/schedule", wikiTeamPage: "2026 TCU Horned Frogs football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "texas-tech", name: "Texas Tech", nick: "Red Raiders", officialDomain: "texastech.com", officialScheduleUrl: "https://texastech.com/sports/football/schedule", wikiTeamPage: "2026 Texas Tech Red Raiders football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "iowa-state", name: "Iowa State", nick: "Cyclones", officialDomain: "cyclones.com", officialScheduleUrl: "https://cyclones.com/sports/football/schedule", wikiTeamPage: "2026 Iowa State Cyclones football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "cincinnati", name: "Cincinnati", nick: "Bearcats", officialDomain: "gobearcats.com", officialScheduleUrl: "https://gobearcats.com/sports/football/schedule", wikiTeamPage: "2026 Cincinnati Bearcats football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big 12" },
  { id: "ucf", name: "UCF", nick: "Knights", officialDomain: "ucfknights.com", officialScheduleUrl: "https://ucfknights.com/sports/football/schedule", wikiTeamPage: "2026 UCF Knights football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big 12" },
  { id: "houston", name: "Houston", nick: "Cougars", officialDomain: "uhcougars.com", officialScheduleUrl: "https://uhcougars.com/sports/football/schedule", wikiTeamPage: "2026 Houston Cougars football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "Big 12" },
  { id: "byu", name: "BYU", nick: "Cougars", officialDomain: "byucougars.com", officialScheduleUrl: "https://byucougars.com/sports/football/schedule", wikiTeamPage: "2026 BYU Cougars football team", wikiNotYetCreated: false, venueTz: "America/Denver", conference2026: "Big 12" },
  { id: "west-virginia", name: "West Virginia", nick: "Mountaineers", officialDomain: "wvusports.com", officialScheduleUrl: "https://wvusports.com/sports/football/schedule", wikiTeamPage: "2026 West Virginia Mountaineers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Big 12" },
  { id: "arizona", name: "Arizona", nick: "Wildcats", officialDomain: "arizonawildcats.com", officialScheduleUrl: "https://arizonawildcats.com/sports/football/schedule", wikiTeamPage: "2026 Arizona Wildcats football team", wikiNotYetCreated: false, venueTz: "America/Phoenix", conference2026: "Big 12" },
  { id: "arizona-state", name: "Arizona State", nick: "Sun Devils", officialDomain: "thesundevils.com", officialScheduleUrl: "https://thesundevils.com/sports/football/schedule", wikiTeamPage: "2026 Arizona State Sun Devils football team", wikiNotYetCreated: false, venueTz: "America/Phoenix", conference2026: "Big 12" },
  { id: "colorado", name: "Colorado", nick: "Buffaloes", officialDomain: "cubuffs.com", officialScheduleUrl: "https://cubuffs.com/sports/football/schedule", wikiTeamPage: "2026 Colorado Buffaloes football team", wikiNotYetCreated: false, venueTz: "America/Denver", conference2026: "Big 12" },
  { id: "notre-dame", name: "Notre Dame", nick: "Fighting Irish", officialDomain: "fightingirish.com", officialScheduleUrl: "https://fightingirish.com/sports/football/schedule", wikiTeamPage: "2026 Notre Dame Fighting Irish football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Independent" },
  { id: "uconn", name: "UConn", nick: "Huskies", officialDomain: "uconnhuskies.com", officialScheduleUrl: "https://uconnhuskies.com/sports/football/schedule", wikiTeamPage: "2026 UConn Huskies football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Independent" },
  { id: "boise-state", name: "Boise State", nick: "Broncos", officialDomain: "broncosports.com", officialScheduleUrl: "https://broncosports.com/sports/football/schedule", wikiTeamPage: "2026 Boise State Broncos football team", wikiNotYetCreated: false, venueTz: "America/Boise", conference2026: "Pac-12" },
  { id: "memphis", name: "Memphis", nick: "Tigers", officialDomain: "gotigersgo.com", officialScheduleUrl: "https://gotigersgo.com/sports/football/schedule", wikiTeamPage: "2026 Memphis Tigers football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "AAC" },
  { id: "appalachian-state", name: "App State", nick: "Mountaineers", officialDomain: "appstatesports.com", officialScheduleUrl: "https://appstatesports.com/sports/football/schedule", wikiTeamPage: "2026 Appalachian State Mountaineers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Sun Belt" },
  { id: "james-madison", name: "James Madison", nick: "Dukes", officialDomain: "jmusports.com", officialScheduleUrl: "https://jmusports.com/sports/football/schedule", wikiTeamPage: null, wikiNotYetCreated: true, venueTz: "America/New_York", conference2026: "Sun Belt" },
  { id: "liberty", name: "Liberty", nick: "Flames", officialDomain: "libertyflames.com", officialScheduleUrl: "https://libertyflames.com/sports/football/schedule", wikiTeamPage: "2026 Liberty Flames football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "CUSA" },
  { id: "coastal-carolina", name: "Coastal Carolina", nick: "Chanticleers", officialDomain: "goccusports.com", officialScheduleUrl: "https://goccusports.com/sports/football/schedule", wikiTeamPage: "2026 Coastal Carolina Chanticleers football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "Sun Belt" },
  { id: "army", name: "Army", nick: "Black Knights", officialDomain: "goarmywestpoint.com", officialScheduleUrl: "https://goarmywestpoint.com/sports/football/schedule", wikiTeamPage: "2026 Army Black Knights football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "AAC" },
  { id: "navy", name: "Navy", nick: "Midshipmen", officialDomain: "navysports.com", officialScheduleUrl: "https://navysports.com/sports/football/schedule", wikiTeamPage: "2026 Navy Midshipmen football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "AAC" },
  { id: "air-force", name: "Air Force", nick: "Falcons", officialDomain: "goairforcefalcons.com", officialScheduleUrl: "https://goairforcefalcons.com/sports/football/schedule", wikiTeamPage: "2026 Air Force Falcons football team", wikiNotYetCreated: false, venueTz: "America/Denver", conference2026: "MWC" },
  { id: "tulane", name: "Tulane", nick: "Green Wave", officialDomain: "tulanegreenwave.com", officialScheduleUrl: "https://tulanegreenwave.com/sports/football/schedule", wikiTeamPage: "2026 Tulane Green Wave football team", wikiNotYetCreated: false, venueTz: "America/Chicago", conference2026: "AAC" },
  { id: "south-florida", name: "USF", nick: "Bulls", officialDomain: "gousfbulls.com", officialScheduleUrl: "https://gousfbulls.com/sports/football/schedule", wikiTeamPage: "2026 South Florida Bulls football team", wikiNotYetCreated: false, venueTz: "America/New_York", conference2026: "AAC" },
  { id: "marshall", name: "Marshall", nick: "Thundering Herd", officialDomain: "herdzone.com", officialScheduleUrl: "https://herdzone.com/sports/football/schedule", wikiTeamPage: null, wikiNotYetCreated: true, venueTz: "America/New_York", conference2026: "Sun Belt" },
  { id: "toledo", name: "Toledo", nick: "Rockets", officialDomain: "utrockets.com", officialScheduleUrl: "https://utrockets.com/sports/football/schedule", wikiTeamPage: null, wikiNotYetCreated: true, venueTz: "America/New_York", conference2026: "MAC" },
  { id: "northern-illinois", name: "Northern Illinois", nick: "Huskies", officialDomain: "niuhuskies.com", officialScheduleUrl: "https://niuhuskies.com/sports/football/schedule", wikiTeamPage: null, wikiNotYetCreated: true, venueTz: "America/Chicago", conference2026: "MWC" },
  { id: "unlv", name: "UNLV", nick: "Rebels", officialDomain: "unlvrebels.com", officialScheduleUrl: "https://unlvrebels.com/sports/football/schedule", wikiTeamPage: "2026 UNLV Rebels football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "MWC" },
  { id: "san-diego-state", name: "San Diego State", nick: "Aztecs", officialDomain: "goaztecs.com", officialScheduleUrl: "https://goaztecs.com/sports/football/schedule", wikiTeamPage: "2026 San Diego State Aztecs football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Pac-12" },
  { id: "fresno-state", name: "Fresno State", nick: "Bulldogs", officialDomain: "gobulldogs.com", officialScheduleUrl: "https://gobulldogs.com/sports/football/schedule", wikiTeamPage: "2026 Fresno State Bulldogs football team", wikiNotYetCreated: false, venueTz: "America/Los_Angeles", conference2026: "Pac-12" },
];

// Alias normalization: slugifySchool output varies by how a source names a team
// ("LSU"->lsu, "Louisiana State"->louisiana-state). Map known variants to the
// canonical id so opponent slugs match across schools + the conference rule.
export const SLUG_ALIASES: Record<string, string> = {
  'louisiana-state': 'lsu', 'southern-california': 'usc', mississippi: 'ole-miss',
  'miami-fl': 'miami', 'miami-florida': 'miami', 'central-florida': 'ucf',
  'brigham-young': 'byu', 'southern-methodist': 'smu', 'texas-christian': 'tcu',
  'nevada-las-vegas': 'unlv', connecticut: 'uconn', 'north-carolina-state': 'nc-state',
  'north-carolina-st': 'nc-state', 'app-state': 'appalachian-state',
  pitt: 'pittsburgh', 'ol-miss': 'ole-miss',
};
export function normalizeSlug(slug: string): string {
  return SLUG_ALIASES[slug] || slug;
}

export const SCHOOLS_2026_BY_ID: Record<string, CfbSchoolConfig2026> =
  Object.fromEntries(SCHOOLS_2026.map((s) => [s.id, s]));
