/* NFL schedule pages are byte-identical to main.
 *
 * The month sections change the MLB date list only. ScheduleBlock also serves
 * the NFL week grid, and that output must not move by a byte, in either of the
 * two places a crawler sees it:
 *   1. the server-rendered HTML, and
 *   2. the RSC flight payload, which for this component is the element tree it
 *      returns: every server element with its key and props, and every
 *      client element (ScheduleRow) with the props it is handed. ScheduleBlock's
 *      own props are never serialized, but everything it returns is.
 *
 * The golden is generated from MAIN's ScheduleBlock (7fd7e7c) and is never
 * regenerated by a passing run. Regenerate only on purpose, from main's code:
 *   git show origin/main:src/components/redesign/ScheduleBlock.tsx > src/components/redesign/ScheduleBlock.tsx
 *   SCHEDULE_GOLDEN_WRITE=1 <test runner> <this file>
 *   git checkout src/components/redesign/ScheduleBlock.tsx
 * The fixture slate is awkward on purpose (bye, TBD flex, London, an away row
 * with no opponent doc, a canceled and a completed game): each is a branch the
 * regular-season filter or the month grouping must never reach on NFL. */
import { test } from 'node:test';
import assert from 'node:assert';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isValidElement, type ReactElement, type ReactNode } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { ScheduleBlock } from '../ScheduleBlock';
import { ScheduleRow } from '../ScheduleRow';
import { LIONS, NFL_CONTEXTS } from './fixtures/schedule-fixtures';

const GOLDEN = join(process.cwd(), 'src/components/redesign/__tests__/fixtures/schedule-nfl.golden.json');

/** Every ScheduleRow element in a tree, by walking element children. */
function rowProps(node: ReactNode, out: unknown[] = []): unknown[] {
  if (Array.isArray(node)) { for (const n of node) rowProps(n, out); return out; }
  if (!isValidElement(node)) return out;
  const el = node as ReactElement<Record<string, unknown>>;
  if (el.type === ScheduleRow) out.push({ key: el.key, props: el.props });
  rowProps(el.props.children as ReactNode, out);
  return out;
}

/** The whole returned tree: element type (tag or component name), key, every
 *  prop, children recursively. What the flight payload is built from. */
function tree(node: ReactNode): unknown {
  if (Array.isArray(node)) return node.map(tree);
  if (!isValidElement(node)) return node === undefined ? '__undefined' : node;
  const el = node as ReactElement<Record<string, unknown>>;
  const type = typeof el.type === 'string' ? el.type : (el.type as { name?: string }).name ?? 'anonymous';
  const { children, ...rest } = el.props;
  const props = JSON.parse(JSON.stringify(rest, (_k, v) => (typeof v === 'function' ? `fn:${v.name}` : v)));
  return { type, key: el.key, props, children: tree(children as ReactNode) };
}

// `today` is a prop the branch adds; main's ScheduleBlock ignores unknown props.
// Two dates bracket the slate so the "remaining game" copy is exercised both
// ways on NFL: neither may change a byte.
const PROPS = [
  { label: 'season ahead', today: '2026-09-01' },
  { label: 'season over', today: '2027-03-01' },
  { label: 'no clock', today: undefined },
];

const snapshot = () =>
  PROPS.map(({ label, today }) => {
    const p = { contexts: NFL_CONTEXTS, team: LIONS, teamName: 'Detroit Lions', today } as Parameters<typeof ScheduleBlock>[0];
    const el = ScheduleBlock(p);
    return {
      label,
      html: renderToStaticMarkup(<ScheduleBlock {...p} />),
      rows: JSON.parse(JSON.stringify(rowProps(el))),
      tree: JSON.parse(JSON.stringify(tree(el))),
    };
  });

test('NFL ScheduleBlock HTML and ScheduleRow props equal the golden taken from main', () => {
  const now = snapshot();
  if (process.env.SCHEDULE_GOLDEN_WRITE === '1') {
    writeFileSync(GOLDEN, JSON.stringify(now, null, 1) + '\n');
    return;
  }
  const golden = JSON.parse(readFileSync(GOLDEN, 'utf8'));
  assert.equal(now.length, golden.length);
  for (let i = 0; i < golden.length; i++) {
    assert.equal(now[i].html, golden[i].html, `${golden[i].label}: NFL HTML drifted from main`);
    assert.deepStrictEqual(now[i].rows, golden[i].rows, `${golden[i].label}: NFL ScheduleRow props (RSC payload) drifted from main`);
    assert.deepStrictEqual(now[i].tree, golden[i].tree, `${golden[i].label}: NFL element tree (RSC payload) drifted from main`);
  }
});

test('the golden is not trivially empty', () => {
  const golden = JSON.parse(readFileSync(GOLDEN, 'utf8'));
  for (const g of golden) {
    assert.equal(g.rows.length, 17, 'all 17 NFL games reach ScheduleRow');
    assert.match(g.html, /Bye week, no game/);
    assert.match(g.html, /week by week/);
    assert.doesNotMatch(g.html, /page-content|<details/);
  }
});
